### ISSUE TITLE
WebView custom CSS

### ISSUE THREAD

**Issue by drakulaboy** [ikws4/WeiJu2-Scripts#1]
Hi, glad to see the module alive, so, i tried for example the script with WebView custom CSS, and i fail, module activated in LSPosed, i choosed the app on what i want the module to be applied, for example Via Browser, i add in the module the app and the script, restarting module and run the Browser, no change on pages, i'm i missing something? also tried the ikws4.system_variable script, no change in DevInfo app

https://user-images.githubusercontent.com/7822898/193449067-b30c68e6-086c-4fbb-979d-6a170b26f6e8.mp4

**Comment by ikws4** [comment]
You need to create your own script and then `require` it.

https://user-images.githubusercontent.com/47056144/193453085-ba1d3fca-b866-4717-aed6-b202141e5f01.mp4

**Comment by drakulaboy** [comment]
oh, so this is how it works, thank you! case closed, module is cool
